### ISSUE TITLE
How to properly auth

### ISSUE THREAD

**Issue by bdlowery** [Errorname/google-docs-mustaches#68]
The docs say to follow this to properly auth: https://github.com/googleapis/google-api-nodejs-client#oauth2-client

But I don't want to use a "Consent screen" because I'm not doing anything with peoples google accounts. People are just simply filling out a form, I'm taking the data, and mapping it 1-1 with the template in my api with nodejs.

Can't i just make a service account for auth?

**Comment by Errorname** [comment]
Hi there !

What this library needs is a token from Google APIs. There are multiple ways to do that, listed here: https://github.com/googleapis/google-api-nodejs-client?tab=readme-ov-file#authentication-and-authorization.

If you do not want OAuth2 because of a Consent Screen, I can suggest using the "API Key" method.

(Note: I haven't tested this method, and this library is not actively maintained, so I can't promise it will work)
